routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\CartDetailController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\AlamatPengirimanController;
use App\Http\Controllers\KonfirmasiController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PagesController::class,'home']);
Route::get('/menu', [PagesController::class,'menu']);
Route::get('/about', [PagesController::class,'about']);
Route::get('/location', [PagesController::class,'location']);
Route::get('/profile', [PagesController::class,'profile']);
Route::get('/payment', [PagesController::class,'payment']);
Route::get('/custom', [PagesController::class,'custom']);




Route::get('/register', [AuthController::class,'register']);
Route::post('/register/check', [AuthController::class,'doRegister']);

Route::get('/login', [AuthController::class,'login']);
Route::post('/login/check', [AuthController::class,'doLogin']);
Route::get('/login/success', [AuthController::class,'successlogin']);
Route::get('/logout', [AuthController::class,'logout']);

Route::get('/registercs', [AuthController::class,'register']);
Route::post('/registercs/check', [AuthController::class,'doRegister']);

Route::get('/logincs', [AuthController::class,'login']);
Route::post('/logincs/check', [AuthController::class,'doLogin']);
Route::get('/logincs/success', [AuthController::class,'successlogin']);
Route::get('/logout', [AuthController::class,'logout']);




Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/product', [ProductController::class, 'productList'])->name('products.list');
// cart
Route::resource('/cart', 'CartController');
Route::patch('kosongkan/{id}', 'CartController@kosongkan');
// cart detail
Route::resource('/cartdetail', 'CartDetailController');
// alamat pengiriman
Route::resource('alamatpengiriman', 'AlamatPengirimanController');
// checkout
Route::get('/checkout', 'CartController@checkout');
Route::get('/payment', 'CartController@payment');
  // route transaksi
  Route::resource('transaksi', 'TransaksiController');
  Route::get('/myorder', 'TransaksiController@index');
  Route::get('/tracking', 'TransaksiController@show');
    // route transaksi
Route::resource('konfirmasi', 'KonfirmasiController');
Route::get('/waiting', 'KonfirmasiController@store');
Route::resource('pengiriman', 'PengirimanController');
 // form laporan
  Route::get('laporan', 'LaporanController@index');
  // proses laporan
  Route::get('/laporan/proses', 'LaporanController@proses');
  Route::get('/laporan/proses_pdf', 'LaporanController@cetak_pdf');


Route::get('product/{product}', [ProductController::class, 'shows'])->name('shows');
Route::get('sofa', [ProductController::class, 'sofa'])->name('sofa');
Route::get('terrace', [ProductController::class, 'terrace'])->name('terrace');
Route::get('dining', [ProductController::class, 'dining'])->name('dining');
Route::get('daybed', [ProductController::class, 'daybed'])->name('daybed');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function() {
    Route::resource('roles', \RoleController::class);
    Route::resource('users', \UserController::class);
    Route::resource('products', \ProductController::class);
    Route::resource('kategori', \KategoriController::class);
});



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::get('/login', [AuthController::class, 'login']);
Route::post('/login/check', [AuthController::class, 'doLogin']);
Route::get('/login/success', [AuthController::class, 'successlogin']);
Route::get('/logout', [AuthController::class, 'logout']);

Route::get('/cart', [App\Http\Controllers\CartController::class, 'create']);
Route::post('/cart_create/{type}/{id}', [App\Http\Controllers\CartController::class, 'store']);
Route::get('/cart_delete/{id}', [App\Http\Controllers\CartController::class, 'destroy']);
Route::get('/summary', [App\Http\Controllers\CheckoutController::class, 'create']);
Route::post('/summary/{type}/{id}', [App\Http\Controllers\CheckoutController::class, 'store']);

resources/views/home.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')


@section('content')
<div class="container">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Dashboard</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        {{-- <li class="breadcrumb-item"><a href="#">Home</a></li> --}}
                        {{-- <li class="breadcrumb-item active">Blank Page</li> --}}
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{ $product->total() }}</h3>

                        <p>Total Produk</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="{{ route('products.index') }}" class="small-box-footer">More info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>{{ $rolesCount }}</h3>

                        <p>Roles</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-users-cog    "></i>
                    </div>
                    <a href="{{ route('roles.index') }}" class="small-box-footer">More info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>{{ $users->count() }}</h3>

                        <p>Total User</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="{{ route('users.index') }}" class="small-box-footer">More info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>65</h3>

                        <p>Unique Visitors</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Produk</h3>

                        <div class="card-tools small">
                            <a href="{{ route('products.index') }}">Selengkapnya</a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0" style="height: 235px;">
                        <table class="table table-head-fixed text-nowrap small">
                            <thead>
                                <tr>
                                    <th>Nama Produk</th>
                                    <th>Kategori</th>
                                    <th>Harga</th>
                                    <th>Keterangan</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($product as $row)
                                    <tr>
                                        <td>{{ $row->nama }}</td>
                                        <td>{{ $row->kategori_id }}</td>
                                        <td class="text-right">{{ number_format($row->harga) }}</td>
                                        <td class="text-right">{{ $row->deskripsi }}</td>
                                    </tr> 
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col-md -->
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Users</h3>

                        <div class="card-tools small">
                            <a href="{{ route('users.index') }}">Selengkapnya</a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0" style="height: 235px;">
                        <table class="table table-head-fixed text-nowrap small">
                            <thead>
                                <tr>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Roles</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $row)
                                    <tr>
                                        <td>{{ $row->name }}</td>
                                        <td>{{ $row->email }}</td>
                                        <td>{{ $row->role }}</td>
                                    </tr> 
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col-md -->
        </div>

    </section>
    <!-- /.content -->
</div>
@endsection