routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\CartDetailController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\AlamatPengirimanController;
use App\Http\Controllers\KonfirmasiController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PagesController::class,'home']);
Route::get('/menu', [PagesController::class,'menu']);
Route::get('/about', [PagesController::class,'about']);
Route::get('/location', [PagesController::class,'location']);
Route::get('/profile', [PagesController::class,'profile']);
Route::get('/payment', [PagesController::class,'payment']);
Route::get('/custom', [PagesController::class,'custom']);




Route::get('/register', [AuthController::class,'register']);
Route::post('/register/check', [AuthController::class,'doRegister']);

Route::get('/login', [AuthController::class,'login']);
Route::post('/login/check', [AuthController::class,'doLogin']);
Route::get('/login/success', [AuthController::class,'successlogin']);
Route::get('/logout', [AuthController::class,'logout']);

Route::get('/registercs', [AuthController::class,'register']);
Route::post('/registercs/check', [AuthController::class,'doRegister']);

Route::get('/logincs', [AuthController::class,'login']);
Route::post('/logincs/check', [AuthController::class,'doLogin']);
Route::get('/logincs/success', [AuthController::class,'successlogin']);
Route::get('/logout', [AuthController::class,'logout']);




Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/product', [ProductController::class, 'productList'])->name('products.list');
// cart
Route::resource('/cart', 'CartController');
Route::patch('kosongkan/{id}', 'CartController@kosongkan');
// cart detail
Route::resource('/cartdetail', 'CartDetailController');
// alamat pengiriman
Route::resource('alamatpengiriman', 'AlamatPengirimanController');
// checkout
Route::get('/checkout', 'CartController@checkout');
Route::get('/payment', 'CartController@payment');
  // route transaksi
  Route::resource('transaksi', 'TransaksiController');
  Route::get('/myorder', 'TransaksiController@index');
  Route::get('/tracking', 'TransaksiController@show');
    // route transaksi
Route::resource('konfirmasi', 'KonfirmasiController');
Route::get('/waiting', 'KonfirmasiController@store');
Route::resource('pengiriman', 'PengirimanController');
 // form laporan
  Route::get('laporan', 'LaporanController@index');
  // proses laporan
  Route::get('/laporan/proses', 'LaporanController@proses');
  Route::get('/laporan/proses_pdf', 'LaporanController@cetak_pdf');


Route::get('product/{product}', [ProductController::class, 'shows'])->name('shows');
Route::get('sofa', [ProductController::class, 'sofa'])->name('sofa');
Route::get('terrace', [ProductController::class, 'terrace'])->name('terrace');
Route::get('dining', [ProductController::class, 'dining'])->name('dining');
Route::get('daybed', [ProductController::class, 'daybed'])->name('daybed');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function() {
    Route::resource('roles', \RoleController::class);
    Route::resource('users', \UserController::class);
    Route::resource('products', \ProductController::class);
    Route::resource('kategori', \KategoriController::class);
});



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::get('/login', [AuthController::class, 'login']);
Route::post('/login/check', [AuthController::class, 'doLogin']);
Route::get('/login/success', [AuthController::class, 'successlogin']);
Route::get('/logout', [AuthController::class, 'logout']);

Route::get('/cart', [App\Http\Controllers\CartController::class, 'create']);
Route::post('/cart_create/{type}/{id}', [App\Http\Controllers\CartController::class, 'store']);
Route::get('/cart_delete/{id}', [App\Http\Controllers\CartController::class, 'destroy']);
Route::get('/summary', [App\Http\Controllers\CheckoutController::class, 'create']);
Route::post('/summary/{type}/{id}', [App\Http\Controllers\CheckoutController::class, 'store']);

app/Models/Konfirmasi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Konfirmasi extends Model
{
    protected $table = 'konfirmasi';
    protected $fillable = [
        'no_invoice',
        'cart_id',
        'user_id',
        'bukti_transfer',
        'total',
        'status',
        'bank',
        'atas_nama',
    ];

    public function cart() {
        return $this->belongsTo('App\Models\Cart', 'cart_id');
    }

}

app/Http/Controllers/KonfirmasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Cart;
use App\Models\Product;
use App\Models\Order;
use App\Models\Konfirmasi;

class KonfirmasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $itemkonfirmasi = konfirmasi::all();
    
        return view('konfirmasi.index', [
            'itemkonfirmasi' => $itemkonfirmasi
        ]);

                }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $this->validate($request, [
            'atas_nama' => 'required',
            'bank' => 'required',
            'bukti_transfer' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',

        ]);
        $input = $request->all();
  
        if ($bukti_transfer = $request->file('bukti_transfer')) {
            $destinationPath = 'image/';
            $profileImage = date('YmdHis') . "." . $bukti_transfer->getClientOriginalExtension();
            $bukti_transfer->move($destinationPath, $profileImage);
            $input['bukti_transfer'] = "$profileImage";
        }
        $itemuser = $request->user();
        $itemcart = Cart::where('status_cart', 'checkout')
        ->where('user_id', $itemuser->id)
        ->first();

            $input['user_id'] = $itemuser->id;
            $input['cart_id'] = $itemcart->id;
            $input['no_invoice'] = $itemcart->no_invoice;
            $input['status'] = 'belum divalidasi';
            $input['total'] = $itemcart->total;
            $itemcart->update(['status_cart' => 'paid']);
            $itemkonfirmasi = Konfirmasi::create($input);

            return view('layouts.waiting');
    }
 
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        $itemkonfirmasi = Konfirmasi::findOrFail($id);
        $itemcart = Cart::where('status_cart', 'paid')
        ->where('id', $itemkonfirmasi->cart_id)
        ->first();
        $itemkonfirmasi->update(['status' => ('Sudah divalidasi')]);
        $itemcart->update(['status_pembayaran' => ('Sudah divalidasi')]);
        
        return redirect()->route('konfirmasi.index')->with('success','Pembayaran berhasil dikonfirmasi');
    }

}

resources/views/konfirmasi/edit.blade.php
@extends('adminlte::page')

@section('title', 'Update Konfirmasi')

@section('content_header')
    <h1 class="m-0 text-dark">Edit Kategori</h1>
@stop

@section('content')
<div class="container-fluid">
  <div class="row">
    <div class="col col-lg-6 col-md-6">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Form Update Kategori</h3>
          <div class="card-tools">
            <a href="{{ route('kategori.index') }}" class="btn btn-sm btn-danger">
              Tutup
            </a>
          </div>
        </div>
        <div class="card-body">
          @if(count($errors) > 0)
          @foreach($errors->all() as $error)
              <div class="alert alert-warning">{{ $error }}</div>
          @endforeach
          @endif
          @if ($message = Session::get('error'))
              <div class="alert alert-warning">
                  <p>{{ $message }}</p>
              </div>
          @endif
          @if ($message = Session::get('success'))
              <div class="alert alert-success">
                  <p>{{ $message }}</p>
              </div>
          @endif
          <form action="{{ route('konfirmasi.update', $itemkonfirmasi->id) }}" method="post">
            @csrf
            {{ method_field('patch') }}
            <div class="form-group">
              <label for="kode_kategori">Kode Kategori</label>
              <input type="text" name="kode_kategori" id="kode_kategori" class="form-control" value={{ $itemkategori->kode_kategori }}>
            </div>
            <div class="form-group">
              <label for="nama_kategori">Nama Kategori</label>
              <input type="text" name="nama_kategori" id="nama_kategori" class="form-control" value={{ $itemkategori->nama_kategori }}>
            </div>
            <div class="form-group">
              <label for="slug_kategori">Slug Kategori</label>
              <input type="text" name="slug_kategori" id="slug_kategori" class="form-control" value={{ $itemkategori->slug_kategori }}>
            </div>
            <div class="form-group">
              <label for="deskripsi_kategori">Deskripsi</label>
              <textarea name="deskripsi_kategori" id="deskripsi_kategori" cols="30" rows="5" class="form-control">{{ $itemkategori->deskripsi_kategori }}</textarea>
            </div>
            <div class="form-group">
              <label for="status">Status</label>
              <select name="status" id="status" class="form-control">
                <option value="publish" {{ $itemkategori->status == 'publish'? 'selected': ''}}>belum divalidasi</option>
                <option value="unpublish" {{ $itemkategori->status == 'unpublish'? 'selected': ''}}>sudah divalidasi</option>
              </select>
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary">Update</button>
              <button type="reset" class="btn btn-warning">Reset</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/konfirmasi/index.blade.php
@extends('adminlte::page')

@section('title', 'Konfirmasi Pembayaran')
<link rel="stylesheet" type="text/css" href="{!! asset('/css/about.css') !!}">
@section('content_header')
    <h1 class="m-0 text-dark">Data Konfirmasi</h1>
@stop
@section('content')
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Data Konfirmasi
          </h3>
        </div>
        <div class="card-body">
          <!-- digunakan untuk menampilkan pesan error atau sukses -->
          @if(count($errors) > 0)
          @foreach($errors->all() as $error)
              <div class="alert alert-warning">{{ $error }}</div>
          @endforeach
          @endif
          @if ($message = Session::get('error'))
              <div class="alert alert-warning">
                  <p>{{ $message }}</p>
              </div>
          @endif
          @if ($message = Session::get('success'))
              <div class="alert alert-success">
                  <p>{{ $message }}</p>
              </div>
          @endif
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Receipt</th>
                  <th>Invoice</th>
                  <th>Nama</th>
                  <th>Bank</th>
                  <th>Total</th>
                  <th>Status Pembayaran</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              @foreach($itemkonfirmasi as $key => $confirm)
                <tr>
                  <td>
                  {{$key+1}}
                  </td>
                  <td>
 <!-- Trigger the Modal -->
<img id="myImg" src="/image/{{ $confirm->bukti_transfer }}"  alt="bukti" style="width:100px;max-width:200px">

<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- The Close Button -->
  <span class="close">&times;</span>

  <!-- Modal Content (The Image) -->
  <img class="modal-content" id="img01">
</td>
                  <td>
                    {{ $confirm->no_invoice }}
                  </td>
                  <td>
                  {{ $confirm->atas_nama }}
                  </td>
                  <td>
                  {{ $confirm->bank }}
                  </td>
                  <td>
                  {{ number_format($confirm->total, 2) }}
                  </td>                  
                  <td>
                  {{ $confirm->status }}
                  </td>
                  <form action="{{ route('konfirmasi.update', $confirm->id) }}" method='post'>
              @csrf
              {{ method_field('patch') }}
                  <td>
                    @if($confirm->status == 'belum divalidasi')
                      <input type="hidden" name="status" id="status" class="form-control" value='Sudah divalidasi'>
                    <button type="submit" class="btn btn-sm btn-primary mb-2">
                    Validasi Pembayaran
                    </a>
                    @else
                    <button type="secondary" class="btn btn-sm btn-secondary mb-2" disabled>
                    Validasi Pembayaran
                    </a>
</form>
                   @endif
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
// Get the modal
var modal = document.getElementById("myModal");

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById("myImg");
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
  modal.style.display = "block";
  modalImg.src = this.src;
  captionText.innerHTML = this.alt;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() { 
  modal.style.display = "none";
}
</script>
@endsection

resources/views/konfirmasi/show.blade.php
@extends('layouts.frontend')
@section('content')
<div class="container-fluid">
  <div class="row">
    <div class="col col-lg-8 col-md-8 mb-2">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Item</h3>
        </div>
        <div class="card-body">
          <!-- digunakan untuk menampilkan pesan error atau sukses -->
          @if(count($errors) > 0)
          @foreach($errors->all() as $error)
              <div class="alert alert-warning">{{ $error }}</div>
          @endforeach
          @endif
          @if ($message = Session::get('error'))
              <div class="alert alert-warning">
                  <p>{{ $message }}</p>
              </div>
          @endif
          @if ($message = Session::get('success'))
              <div class="alert alert-success">
                  <p>{{ $message }}</p>
              </div>
          @endif
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>
                    No
                  </th>
                  <th>
                    Nama
                  </th>
                  <th>
                    Harga
                  </th>
                  <th>
                  </th>
                  <th>
                  </th>
                  <th>
                    Qty
                  </th>
                  <th>
                    Subtotal
                  </th>
                </tr>
              </thead>
              <tbody>
              @foreach($itemorder->cart->detail as $detail)
                <tr>
                  <td>
                  {{ $no++ }}
                  </td>
                  <td>
                  {{ $detail->product->nama }}
                  </td>
                  <td>
                  {{ number_format($detail->harga, 2) }}
                  </td>
                  <td>
</td>
<td>
</td>
                  <td>
                  {{ $detail->quantity }}
                  </td>
                  <td>
                  {{ number_format($detail->subtotal, 2) }}
                  </td>
                </tr>
              @endforeach
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td>
                    <b>Total</b>
                  </td>
                  <td>
                    <b>
                    {{ number_format($itemorder->cart->total, 2) }}
                    </b>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer">
          <a href="{{ route('transaksi.index') }}" class="btn btn-sm btn-danger">Tutup</a>
        </div>
      </div>
      <div class="card">
        <div class="card-header">Alamat Pengiriman</div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-stripped">
              <thead>
                <tr>
                  <th>Nama Penerima</th>
                  <th>Alamat</th>
                  <th>No tlp</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    {{ $itemorder->nama_penerima }}
                  </td>
                  <td>
                    {{ $itemorder->alamat }}<br />
                    {{ $itemorder->kelurahan}}, {{ $itemorder->kecamatan}}<br />
                    {{ $itemorder->kota}}, {{ $itemorder->provinsi}} - {{ $itemorder->kodepos}}
                  </td>
                  <td>
                    {{ $itemorder->no_tlp }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col col-lg-4 col-md-4">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Ringkasan</h3>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td>
                    Total
                  </td>
                  <td class="text-right">
                    {{ number_format($itemorder->cart->total, 2) }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Subtotal
                  </td>
                  <td class="text-right">
                  {{ number_format($itemorder->cart->subtotal, 2) }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Ongkir
                  </td>
                  <td class="text-right">
                  {{ number_format($itemorder->cart->ongkir, 2) }}
                  </td>
                </tr>
                <tr>
                  <td>
                    No. Resi
                  </td>
                  <td class="text-right">
                  {{ number_format($itemorder->cart->no_resi, 2) }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Status Pembayaran
                  </td>
                  <td class="text-right">
                  {{ $itemorder->cart->status_pembayaran }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Status Pengiriman
                  </td>
                  <td class="text-right">
                  {{ $itemorder->cart->status_pengiriman }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection