routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\CartDetailController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\AlamatPengirimanController;
use App\Http\Controllers\KonfirmasiController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PagesController::class,'home']);
Route::get('/menu', [PagesController::class,'menu']);
Route::get('/about', [PagesController::class,'about']);
Route::get('/location', [PagesController::class,'location']);
Route::get('/profile', [PagesController::class,'profile']);
Route::get('/payment', [PagesController::class,'payment']);
Route::get('/custom', [PagesController::class,'custom']);




Route::get('/register', [AuthController::class,'register']);
Route::post('/register/check', [AuthController::class,'doRegister']);

Route::get('/login', [AuthController::class,'login']);
Route::post('/login/check', [AuthController::class,'doLogin']);
Route::get('/login/success', [AuthController::class,'successlogin']);
Route::get('/logout', [AuthController::class,'logout']);

Route::get('/registercs', [AuthController::class,'register']);
Route::post('/registercs/check', [AuthController::class,'doRegister']);

Route::get('/logincs', [AuthController::class,'login']);
Route::post('/logincs/check', [AuthController::class,'doLogin']);
Route::get('/logincs/success', [AuthController::class,'successlogin']);
Route::get('/logout', [AuthController::class,'logout']);




Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/product', [ProductController::class, 'productList'])->name('products.list');
// cart
Route::resource('/cart', 'CartController');
Route::patch('kosongkan/{id}', 'CartController@kosongkan');
// cart detail
Route::resource('/cartdetail', 'CartDetailController');
// alamat pengiriman
Route::resource('alamatpengiriman', 'AlamatPengirimanController');
// checkout
Route::get('/checkout', 'CartController@checkout');
Route::get('/payment', 'CartController@payment');
  // route transaksi
  Route::resource('transaksi', 'TransaksiController');
  Route::get('/myorder', 'TransaksiController@index');
  Route::get('/tracking', 'TransaksiController@show');
    // route transaksi
Route::resource('konfirmasi', 'KonfirmasiController');
Route::get('/waiting', 'KonfirmasiController@store');
Route::resource('pengiriman', 'PengirimanController');
 // form laporan
  Route::get('laporan', 'LaporanController@index');
  // proses laporan
  Route::get('/laporan/proses', 'LaporanController@proses');
  Route::get('/laporan/proses_pdf', 'LaporanController@cetak_pdf');


Route::get('product/{product}', [ProductController::class, 'shows'])->name('shows');
Route::get('sofa', [ProductController::class, 'sofa'])->name('sofa');
Route::get('terrace', [ProductController::class, 'terrace'])->name('terrace');
Route::get('dining', [ProductController::class, 'dining'])->name('dining');
Route::get('daybed', [ProductController::class, 'daybed'])->name('daybed');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function() {
    Route::resource('roles', \RoleController::class);
    Route::resource('users', \UserController::class);
    Route::resource('products', \ProductController::class);
    Route::resource('kategori', \KategoriController::class);
});



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::get('/login', [AuthController::class, 'login']);
Route::post('/login/check', [AuthController::class, 'doLogin']);
Route::get('/login/success', [AuthController::class, 'successlogin']);
Route::get('/logout', [AuthController::class, 'logout']);

Route::get('/cart', [App\Http\Controllers\CartController::class, 'create']);
Route::post('/cart_create/{type}/{id}', [App\Http\Controllers\CartController::class, 'store']);
Route::get('/cart_delete/{id}', [App\Http\Controllers\CartController::class, 'destroy']);
Route::get('/summary', [App\Http\Controllers\CheckoutController::class, 'create']);
Route::post('/summary/{type}/{id}', [App\Http\Controllers\CheckoutController::class, 'store']);

resources/views/layouts/about.blade.php
@extends('layouts/index')

@section('head')
<link rel="stylesheet" type="text/css" href="{!! asset('/css/about.css') !!}">

@endsection
@section('body')

<div class="container-fluid">
  <h1 style="font-family: Poppins;font-weight: 500;font-size: 60px;color :#B81900; margin: auto;width: 326px;">About Us</h1>
  <div class="row">
    <P class="isi">
    Fellanova Furniture hadir untuk memenuhi kebutuhan dan kepuasan besar anda semua akan furnitur yang terbuat dari rotan sintetik/plastik. 
    Furniture buatan asli Indonesia (Cirebon) yang sudah mendunia.<br><br> <br>
      ✆ : 08122853636 <br>  ✉ : <a href=mailto:fellanov@gmail.com> fellanov@gmail.com </a></P>

    <div class="column" style="background-color:white;padding-left:60px;">
      <div id="myCarousel" class="carousel-fade" data-ride="carousel" data-interval="4000">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="container">
          <div class="carousel-inner" style="margin-left:60px;">
            <div class="item active">
              <img src="/image/brown sofa.png" alt="about us" style="width:35%;border-radius:30px;">
            </div>

            <div class="item">
              <img src="/image/dining round.png" alt="about us" style="width:35%;border-radius:30px;">
            </div>

            <div class="item">
              <img src="/image/L sofa.png" alt="about us" style="width:35%;border-radius:30px;">
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection

resources/views/layouts/alamatpengiriman.blade.php
@extends('layouts.template')
@section('content')
<div class="container">
  <div class="row">
    <div class="col col-12 mb-2">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col">
              Alamat Pengiriman
            </div>
            <div class="col-auto">
              <a href="{{ URL::to('checkout') }}" class="btn btn-sm btn-danger">
                Tutup
              </a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-stripped">
              <thead>
                <tr>
                  <th>Nama Penerima</th>
                  <th>Alamat</th>
                  <th>No tlp</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              @foreach($itemalamatpengiriman as $pengiriman)
                <tr>
                  <td>
                    {{ $pengiriman->nama_penerima }}
                  </td>
                  <td>
                    {{ $pengiriman->alamat }}<br />
                    {{ $pengiriman->kota}},{{ $pengiriman->kodepos}}
                  </td>
                  <td>
                    {{ $pengiriman->no_tlp }}
                  </td>
                  <td>
                    <form action="{{ route('alamatpengiriman.update',$pengiriman->id) }}" method="post">
                      @method('patch')
                      @csrf()
                      @if($pengiriman->status == 'utama')
                      <button type="submit" class="btn btn-primary btn-sm" disabled>Set Utama</button>
                      @else
                      <button type="submit" class="btn btn-primary btn-sm">Set Utama</button>
                      @endif
                    </form>
                  </td>
                </tr>
              @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col col-8">
      <div class="card">
        <div class="card-header">
          Form Alamat Pengiriman
        </div>
        <div class="card-body">
          @if(count($errors) > 0)
          @foreach($errors->all() as $error)
              <div class="alert alert-warning">{{ $error }}</div>
          @endforeach
          @endif
          @if ($message = Session::get('error'))
              <div class="alert alert-warning">
                  <p>{{ $message }}</p>
              </div>
          @endif
          @if ($message = Session::get('success'))
              <div class="alert alert-success">
                  <p>{{ $message }}</p>
              </div>
          @endif
          <form action="{{ route('alamatpengiriman.store') }}" method="post">
            @csrf()
            <div class="row">
              <div class="col">
                <div class="form-group">
                  <label for="nama_penerima">Nama Penerima</label>
                  <input type="text" name="nama_penerima" class="form-control" value={{old('nama_penerima') }}>
                </div>
                <div class="form-group">
                  <label for="alamat">Alamat</label>
                  <input type="text" name="alamat" class="form-control" value={{old('alamat') }}>
                </div>
                <div class="form-group">
                  <label for="no_tlp">No Tlp</label>
                  <input type="text" name="no_tlp" class="form-control" value={{old('no_tlp') }}>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <label for="kota">Kota</label>
                  <input type="text" name="kota" class="form-control" value={{old('kota') }}>
                </div>
                <div class="form-group">
                  <label for="kodepos">Kodepos</label>
                  <input type="text" name="kodepos" class="form-control" value={{old('kodepos') }}>
                </div>
                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/checkout.blade.php
@extends('layouts/base')

@section('head')
<link rel="stylesheet" type="text/css" href="{!! asset('/css/cart.css') !!}">
@endsection

@section('body')
<div class="container-fluid">
  <p> <br> <br> </p>

  <div class='steps-container' style="margin-left:410px;position:relative;">
        <div class='steps active'>
            <span style="font-family:montserrat;font-size:20px;font-weight:700">CART</span>
        </div>
        <div class='steps active'>
            <span style="font-family:montserrat;font-size:20px;font-weight:700">CHECKOUT</span>
        </div>
        <div class='steps'>
            <span style="font-family:montserrat;font-size:20px;font-weight:700">PAYMENT</span>
        </div>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col col-8">
      @if(count($errors) > 0)
      @foreach($errors->all() as $error)
          <div class="alert alert-warning">{{ $error }}</div>
      @endforeach
      @endif
      @if ($message = Session::get('error'))
          <div class="alert alert-warning">
              <p>{{ $message }}</p>
          </div>
      @endif
      @if ($message = Session::get('success'))
          <div class="alert alert-success">
              <p>{{ $message }}</p>
          </div>
      @endif
      <div class="row mb-2">
        <div class="col col-12 mb-2">
          <div class="card">
            <div class="card-header">
              Item
            </div>
            <div class="card-body">
              <table class="table table-stripped">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Produk</th>
                    <th>Harga</th>
                    <th>Jumlah</th>
                    <th>Subtotal</th>
                  </tr>
                </thead>
                <tbody  style="font-family:montserrat;font-weight:700;">
                  @foreach($itemcart->detail as $detail)
                  <tr>
                    <td>
                    {{ $no++ }}
                    </td>
                    <td>
                    <div class="row">
                            <div class="col-sm-5 hidden-xs"><img src="/image/{{ $detail->gambar }}" class="img-thumbnail" width="200" height="200"></div>
                            <div class="col-sm-5">
                            <b> {{ $detail->product->nama }} </b>
                            </div>
                    <br />
                    </td>
                    <td>
                    {{ number_format($detail->harga, 2) }}
                    </td>
                    <td>
                    {{ number_format($detail->quantity) }}
                    </td>
                    <td>
                    {{ number_format($detail->subtotal, 2) }}
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col col-12">
          <div class="card">
            <div class="card-header">Alamat Pengiriman</div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-stripped">
                  <thead>
                    <tr>
                      <th>Nama Penerima</th>
                      <th>Alamat</th>
                      <th>No tlp</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                  @if($itemalamatpengiriman)
                    <tr>
                      <td>
                        {{ $itemalamatpengiriman->nama_penerima }}
                      </td>
                      <td>
                        {{ $itemalamatpengiriman->alamat }}<br />
                        {{ $itemalamatpengiriman->kota}} - {{ $itemalamatpengiriman->kodepos}}
                      </td>
                      <td>
                        {{ $itemalamatpengiriman->no_tlp }}
                      </td>
                      <td>
                        <a href="{{ route('alamatpengiriman.index') }}" class="btn btn-success btn-sm">
                          Ubah Alamat
                        </a>                        
                      </td>
                    </tr>
                  @endif
                  </tbody>
                </table>
              </div>
            </div>
            <div class="card-footer">
              <a href="{{ route('alamatpengiriman.index') }}" class="btn btn-sm btn-primary">
                Tambah Alamat
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col col-4">
      <div class="card">
      <div class="card-header">
          Ringkasan
        </div>
        <div class="card-body">
          <table class="table">
            <tr>
              <td>No Invoice</td>
              <td class="text-right">
                {{ $itemcart->no_invoice }}
              </td>
            </tr>
            <tr>
              <td>Subtotal</td>
              <td class="text-right">
                {{ number_format($itemcart->subtotal, 2) }}
              </td>
            </tr>
            <tr>
              <td>ongkir</td>
              <td class="text-right">
                {{ number_format($itemcart->ongkir, 2) }}
              </td>
            </tr>
            <tr>
              <td>Total</td>
              <td class="text-right">
                {{ number_format($itemcart->total, 2) }}
              </td>
            </tr>
          </table>
        </div>
        <div class="card-footer">
          <form action="{{ route('transaksi.store') }}" method="post">
            @csrf()
            <button type="success" class="btn btn-danger btn-block">Confirm Order</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/layouts/daybed.blade.php
@extends('layouts.frontend')
<title>Fellanova Furniture - Daybed</title>
@section('content')

    <div class="container px-6 mx-auto">
        <div>
        <ul class="nav nav-pills">    
  <li >
    <a href="product">Semua Produk</a>
  </li>
  <li><a href="{{ route('sofa') }}">Sofa</a></li>
  <li><a href="{{ route('terrace') }}">Kursi Teras</a></li>
  <li><a href="{{ route('dining') }}">Meja & Kursi Makan</a></li>
  <li class="active" ><a href="{{ route('daybed') }}">Daybed</a></li>
</ul>
</div>



<div class="grid grid-cols-1 gap-6 mt-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            
            @foreach ($products as $product)
            @if ($product->kategori_id=='4')
            <a href ="{{ route('shows', $product->id ) }}">
            <div class="w-full max-w-sm mx-auto overflow-hidden rounded-md shadow-md">
                <img src="/image/{{ $product->gambar }}" alt="" class="w-full">
                <div class="flex items-end justify-end w-full bg-cover">
                    
                </div>
                <div class="px-5 py-3">
                    <h3 class="text-gray-700 uppercase">{{ $product->nama }}</h3>
                    <span class="mt-2 text-gray-500">Rp.{{ $product->harga }}</span>
                    <form action="{{ route('cartdetail.store') }}" method="POST">
                       @csrf
                     <input type="hidden" name="product_id" value={{$product->id}}>
                     @if(isset(Auth::user()->email))
                        <button class="px-4 py-2 text-white bg-blue-800 rounded">Add To Cart</button>
                        @endif
</form>
                </div>
                
            </div>
            @endif
</a>
            @endforeach
        </div>
    </div>
@endsection

resources/views/layouts/dining.blade.php
@extends('layouts.frontend')
<title>Fellanova Furniture - Dining</title>
@section('content')

    <div class="container px-6 mx-auto">
        <div>
        <ul class="nav nav-pills">
            
  <li >
    <a href="product">Semua Produk</a>
  </li>
  <li ><a href="{{ route('sofa') }}">Sofa</a></li>
  <li><a href="terrace">Kursi Teras</a></li>
  <li class="active" ><a href="dining">Meja & Kursi Makan</a></li>
  <li><a href="{{ route('daybed') }}">Daybed</a></li>
</ul>
</div>
<div class="grid grid-cols-1 gap-6 mt-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            
            @foreach ($products as $product)
            @if ($product->kategori_id=='3')
            <a href ="{{ route('shows', $product->id ) }}">
            <div class="w-full max-w-sm mx-auto overflow-hidden rounded-md shadow-md">
                <img src="/image/{{ $product->gambar }}" alt="" class="w-full">
                <div class="flex items-end justify-end w-full bg-cover">
                    
                </div>
                <div class="px-5 py-3">
                    <h3 class="text-gray-700 uppercase">{{ $product->nama }}</h3>
                    <span class="mt-2 text-gray-500">Rp.{{ $product->harga }}</span>
                    <form action="{{ route('cartdetail.store') }}" method="POST">
                       @csrf
                     <input type="hidden" name="product_id" value={{$product->id}}>
                     @if(isset(Auth::user()->email))
                        <button class="px-4 py-2 text-white bg-blue-800 rounded">Add To Cart</button>
                        @endif
</form>
                </div>
                
            </div>
            @endif
</a>
            @endforeach
        </div>
    </div>
@endsection

resources/views/layouts/tracking.blade.php
@extends('layouts/base')

@section('head')
<link rel="stylesheet" type="text/css" href="{!! asset('/css/waiting.css') !!}">
@endsection

@section('body')
@section('content')
<div class="container-fluid">
<div class="content-wrapper"> 

<div class="track">
@if($itemorder->cart->status_pengiriman == 'belum')
                <div class="step activne"> <span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Pembayaran Berhasil</span> </div>
                <div class="step active"> <span class="icon"> <i class="fa fa-archive"></i> </span> <span class="text">Pesananmu sedang disiapkan</span> </div>
                <div class="step"> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Pesanan dikirim </span> </div>
           
@elseif($itemorder->cart->status_pengiriman == 'sudah')
                <div class="step active"> <span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Pembayaran Berhasil</span> </div>
                <div class="step active"> <span class="icon"> <i class="fa fa-archive"></i> </span> <span class="text">Pesananmu sedang disiapkan</span> </div>
                <div class="step active"> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Pesanan dikirim </span> </div>
            
@endif </div>
  <div class="row">
    <div class="col col-lg-8 col-md-8 mb-2">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Item</h3>
        </div>
        <div class="card-body">
          <!-- digunakan untuk menampilkan pesan error atau sukses -->
          @if(count($errors) > 0)
          @foreach($errors->all() as $error)
              <div class="alert alert-warning">{{ $error }}</div>
          @endforeach
          @endif
          @if ($message = Session::get('error'))
              <div class="alert alert-warning">
                  <p>{{ $message }}</p>
              </div>
          @endif
          @if ($message = Session::get('success'))
              <div class="alert alert-success">
                  <p>{{ $message }}</p>
              </div>
          @endif
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>
                    No
                  </th>
                  <th>
                    Nama
                  </th>
                  <th>
                    Harga
                  </th>
                  <th>
                  </th>
                  <th>
                  </th>
                  <th>
                    Qty
                  </th>
                  <th>
                    Subtotal
                  </th>
                </tr>
              </thead>
              <tbody>
              @foreach($itemorder->cart->detail as $detail)
                <tr>
                  <td>
                  {{ $no++ }}
                  </td>
                  <td>
                  {{ $detail->product->nama }}
                  </td>
                  <td>
                  {{ number_format($detail->harga, 2) }}
                  </td>
                  <td>
</td>
<td>
</td>
                  <td>
                  {{ $detail->quantity }}
                  </td>
                  <td>
                  {{ number_format($detail->subtotal, 2) }}
                  </td>
                </tr>
              @endforeach
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td>
                    <b>Total</b>
                  </td>
                  <td>
                    <b>
                    {{ number_format($itemorder->cart->total, 2) }}
                    </b>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer">
          <a href="{{ route('transaksi.index') }}" class="btn btn-sm btn-danger">Tutup</a>
        </div>
      </div>
      <div class="card">
        <div class="card-header">Alamat Pengiriman</div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-stripped">
              <thead>
                <tr>
                  <th>Nama Penerima</th>
                  <th>Alamat</th>
                  <th>No tlp</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    {{ $itemorder->nama_penerima }}
                  </td>
                  <td>
                    {{ $itemorder->alamat }}<br />
                    {{ $itemorder->kelurahan}}, {{ $itemorder->kecamatan}}<br />
                    {{ $itemorder->kota}}, {{ $itemorder->provinsi}} - {{ $itemorder->kodepos}}
                  </td>
                  <td>
                    {{ $itemorder->no_tlp }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col col-lg-4 col-md-4">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Ringkasan</h3>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td>
                    Total
                  </td>
                  <td class="text-right">
                    {{ number_format($itemorder->cart->total, 2) }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Subtotal
                  </td>
                  <td class="text-right">
                  {{ number_format($itemorder->cart->subtotal, 2) }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Ongkir
                  </td>
                  <td class="text-right">
                  {{ number_format($itemorder->cart->ongkir, 2) }}
                  </td>
                </tr>

                <tr>
                  <td>
                    Status Pembayaran
                  </td>
                  <td class="text-right">
                  {{ $itemorder->cart->status_pembayaran }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Status Pengiriman
                  </td>
                  <td class="text-right">
                  {{ $itemorder->cart->status_pengiriman }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Estimasi
                  </td>
                  <td class="text-right">
                  {{ $itempengiriman->estimasi }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Tanggal Pengiriman
                  </td>
                  <td class="text-right">
                  {{ $itempengiriman->tgl_pengiriman }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
@endsection